# A sample Gemfile
source "https://rubygems.org"

gem 'rake'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'nokogiri'
gem 'aws-sdk', '< 2.0'
group :development do
  gem 'sqlite3'
end

group :production do
  gem 'pg'
end
